#!/usr/bin/env bash

LATEST_ASDF_VERSION="$(curl --silent "https://api.github.com/repos/asdf-vm/asdf/releases/latest" | jq -r .tag_name)"

if ! [ -e "$HOME/.asdf" ]; then
    git clone https://github.com/asdf-vm/asdf.git "$HOME/.asdf" --branch "$LATEST_ASDF_VERSION"
fi

cat - << EOS > "$HOME/.asdfrc"
legacy_version_file = yes
EOS
