#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

brew install \
  aws-cdk

brew tap weaveworks/tap
brew install weaveworks/tap/eksctl

curl "https://d1vvhvl2y92vvt.cloudfront.net/AWSCLIV2.pkg" -o "$HOME/Downloads/AWSCLIV2.pkg"
sudo installer -pkg $HOME/Downloads/AWSCLIV2.pkg -target /
