#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Replace GNU/Linux commands with system default
# ref https://qiita.com/eumesy/items/3bb39fc783c8d4863c5f
brew install \
  coreutils \
  ed \
  findutils \
  gawk \
  gnu-sed \
  gnu-tar \
  grep

# Install commands and softwares
brew install \
  aqua \
  ast-grep \
  atuin \
  awscli \
  bat \
  broot \
  colima \
  curl \
  diffutils \
  dotter \
  duckdb \
  duf \
  dust \
  ed \
  eza \
  fd \
  fx \
  fzf \
  git \
  gzip \
  helix \
  hurl \
  jq \
  mise \
  openssl \
  pt \
  pwgen \
  starship \
  tealdeer \
  tflint \
  tree \
  trivy \
  unzip \
  wget \
  xan \
  yq \
  zoxide

# Docker
brew install \
  dive \
  docker \
  docker-buildx \
  docker-completion \
  docker-compose-completion

brew install --cask ghostty
