#!/usr/bin/env bash

brew install \
  difftastic \
  diff-so-fancy \
  gh \
  ghq \
  git \
  gunupg2 \
  libfido2 \
  pinentry-mac \
  tig

curl -L https://github.com/takaaki-kasai/git-foresta/raw/master/git-foresta -o /usr/local/bin/git-foresta
chmod +x /usr/local/bin/git-foresta

ln -s "$(dirname "$(cd "$(dirname "$0")"; pwd -P)")/.gitconfig" "$HOME/.gitconfig"
ln -s "$(dirname "$(cd "$(dirname "$0")"; pwd -P)")/.gitignore_global" "$HOME/.gitignore"
