#!/usr/bin/env bash

DOTFILES_SOURCE_DIRECTORY=$HOME/works/src/github.com/hosht/dotfiles/

git clone https://github.com/hosht/dotfiles.git $DOTFILES_SOURCE_DIRECTORY

cd $DOTFILES_SOURCE_DIRECTORY/init/

# Run brew first
./brew
./git
./ruby
# ./vim
./tmux
./zsh
./macos
./mas
