#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo 'Start'

DOTFILES_SOURCE_DIRECTORY=$HOME/works/src/github.com/hosht/dotfiles/

git clone https://github.com/hosht/dotfiles.git $DOTFILES_SOURCE_DIRECTORY

cd $DOTFILES_SOURCE_DIRECTORY/init/

# Run brew first
./brew
./aws
./git
./ruby
# ./vim
./tmux
./zsh
./macos
./mas
./misc

echo 'Done. Restart computer to apply changes'
