#!/usr/bin/env bash


# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Before run mas command you must sign into App Store

brew install mas

# 1Password 7
# Instapaper
# Keka
# Keynote
# Numbers
# Pages
# Vimari
mas install  \
  1333542190 \
  1481302432 \
  470158793  \
  409183694  \
  409203825  \
  409201541  \
  1480933944 \
