#!/usr/bin/env bash

RBENV_ROOT=$HOME/.anyenv/envs/rbenv

$HOME/.anyenv/bin/anyenv install rbenv
git clone https://github.com/rbenv/rbenv-default-gems.git $RBENV_ROOT/plugins/rbenv-default-gems

echo 'gem: --no-document' > $HOME/.gemrc

cat - << EOS > $RBENV_ROOT/default-gems
brakeman
debase
debug
reek
rubocop
ruby-debug-ide
solargraph
EOS
