#!/usr/bin/env bash

RBENV_ROOT=$HOME/.anyenv/envs/rbenv

$HOME/.anyenv/bin/anyenv install rbenv
git clone https://github.com/ianheggie/rbenv-binstubs.git $RBENV_ROOT/plugins/rbenv-binstubs
git clone https://github.com/rbenv/rbenv-default-gems.git $RBENV_ROOT/plugins/rbenv-default-gems

echo 'gem: --no-document' > $HOME/.gemrc

cat - << EOS > $RBENV_ROOT/default-gems
bundler
rubocop
pry
solargraph
ruby-debug-ide
debase
EOS
