#!/usr/bin/env bash

brew install vim

BASEDIR=$(dirname "$0")

ln -s $(dirname "$(cd "$(dirname "$0")"; pwd -P)")/.vim $HOME/.vim
ln -s $(dirname "$(cd "$(dirname "$0")"; pwd -P)")/.vimrc $HOME/.vimrc
mkdir $HOME/.vim/backup
