#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

brew install \
  zsh \
  zsh-completion

mkdir ~/.zplugin
git clone https://github.com/zdharma/zplugin.git ~/.zplugin/bin

ln -s $(dirname "$(cd "$(dirname "$0")"; pwd -P)")/.zshenv $HOME/.zshenv
ln -s $(dirname "$(cd "$(dirname "$0")"; pwd -P)")/.zshrc $HOME/.zshrc

echo '/usr/local/bin/zsh' | sudo tee -a /etc/shells > /dev/null
sudo chsh -s /usr/local/bin/zsh $(id -un)
chmod 755 /usr/local/share/
