#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

brew install \
  zsh \

echo '/opt/homebrew/bin/zsh' | sudo tee -a /etc/shells > /dev/null
sudo chsh -s /opt/homebrew/bin/zsh "$(id -un)"
chmod 755 /opt/homebrew/share/
