# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 320
    lines: 48

  position:
   x: 0
   y: 0

  padding:
    x: 1
    y: 0

  dynamic_padding: false

  decorations: none

  start_maximized: false

scrolling:
  history: 10000

  multiplier: 3

  faux_multiplier: 3

  auto_scroll: false

tabspaces: 4

font:
  normal:
    family: Source Han Code JP

  size: 12.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

render_timer: false

persistent_logging: false

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x1e282d'
    foreground: '0xc4c7d1'

  normal:
    black:   '0x666666'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x80cbc4'
    magenta: '0xff2f90'
    cyan:    '0xaeddff'
    white:   '0xffffff'

  bright:
    black:   '0xff262b'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x7dc6bf'
    magenta: '0x6c71c4'
    cyan:    '0x35434d'
    white:   '0xffffff'

  indexed_colors: []

visual_bell:
  animation: EaseOutExpo
  duration: 0
  color: '0xffffff'

background_opacity: 1.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

  url:
    modifiers: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  save_to_clipboard: false

dynamic_title: true

cursor:
  style: Block

  unfocused_hollow: true

live_config_reload: true

enable_experimental_conpty_backend: false

alt_send_esc: false

key_bindings:
  # (Windows/Linux only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Add,      mods: Control,       action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  # (macOS only)
  - { key: Key0,   mods: Command, action: ResetFontSize    }
  - { key: Add,    mods: Command, action: IncreaseFontSize }
  - { key: Minus,  mods: Command, action: DecreaseFontSize }
  - { key: K,      mods: Command, action: ClearHistory     }
  - { key: K,      mods: Command, chars: "\x0c"            }
  - { key: V,      mods: Command, action: Paste            }
  - { key: C,      mods: Command, action: Copy             }
  - { key: H,      mods: Command, action: Hide             }
  - { key: Q,      mods: Command, action: Quit             }
  - { key: W,      mods: Command, action: Quit             }

  - { key: Space,  mods: Alt,     action: Hide             }

  - { key: L,        mods: Control, action: ClearLogNotice                   }
  - { key: L,        mods: Control, chars: "\x0c"                            }
