# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# relaod configuration
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# decrease key stroke
set -sg escape-time 1

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off

# Vi mode for copy
unbind [
bind v copy-mode\; display "Copy mode!"
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# less command like page up and down
unbind -T copy-mode-vi b
bind -T copy-mode-vi b send -X page-up
unbind -T copy-mode-vi f
bind -T copy-mode-vi f send -X page-down


# New and kill window
bind -n C-n new-window
bind -n C-w kill-window

# | split pane horizontal
bind | split-window -h

# - split pane vertical
bind - split-window -v

# Move panes and windows
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n C-] next-window
bind -n C-\\ previous-window

# Change pane size
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Session
bind s choose-session
bind t choose-tree
bind w choose-tree -w
bind C new-session -c "#{pane_current_path}"
bind K kill-session
bind P switch-client -p
bind N switch-client -n

# Toggle Synchronize panes
bind B setw synchronize-panes on
bind b setw synchronize-panes off


# Status bar
set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""

# Theme
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=black,bg=blue,bold] #S #[bg=default] "
set -g status-right "#[fg=blue]#{?client_prefix,PREFIX ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg=brightblack] #I:#W "
set -g window-status-current-format "#[fg=blue,bold] #I:#W "
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"
set -g message-style "bg=default,fg=blue"
set -g message-command-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
setw -g clock-mode-colour blue
